theme: jekyll-theme-minimal
title: Soleil Young
avatar: https://pbs.twimg.com/profile_images/1525976820495142912/FF9qlpe__400x400.jpg
description: Graduate Candidate at University of Wisconsin-Madison

footer-links:
  email: soleil.ev.young@gmail.com
  github: soleilyoung
  twitter: soleilsolay
  googlescholar : "https://scholar.google.com/citations?hl=en&user=3TKNQFQAAAAJ"
  orcid : "https://orcid.org/my-orcid?orcid=0000-0002-5309-7892"
