theme: jekyll-theme-minimal
title: Soleil Young
avatar: https://64.media.tumblr.com/1410c810e63304ffa8a2aa7172456a6f/d4ec4f1e3fed5a0a-cb/s2048x3072/50244d870875670eeb5e3f4e9825ee31cff458f0.pnj
description: Graduate Candidate at University of Wisconsin-Madison

footer-links:
  email: soleil.ev.young@gmail.com
  github: soleilyoung
  twitter: soleilsolay
  googlescholar : "https://scholar.google.com/citations?hl=en&user=3TKNQFQAAAAJ"
  orcid : "https://orcid.org/my-orcid?orcid=0000-0002-5309-7892"
